name: Node.js CI 

on:
  push:
    branches: [ deployment-setup ]

jobs:
  build:
    runs-on: self-hosted
  
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
          node-version: 16.x
    - run: |
        pwd